In [ ]:
https://pypi.org/project/rank-bm25/
    

In [1]:
!pip install rank-bm25


[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import rank_bm25

In [3]:
help(rank_bm25)

Help on module rank_bm25:

NAME
    rank_bm25

CLASSES
    builtins.object
        BM25
            BM25L
            BM25Okapi
            BM25Plus
    
    class BM25(builtins.object)
     |  BM25(corpus, tokenizer=None)
     |  
     |  Methods defined here:
     |  
     |  __init__(self, corpus, tokenizer=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  get_batch_scores(self, query, doc_ids)
     |  
     |  get_scores(self, query)
     |  
     |  get_top_n(self, query, documents, n=5)
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  __dict__
     |      dictionary for instance variables (if defined)
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
    
    class BM25L(BM25)
     |  BM25L(corpus, tokenizer=None, k1=1.5, b=0.75, delta=0.5)
     |  
     |  Method resolution order:
     |      BM25

In [4]:
from rank_bm25 import BM25Okapi

In [5]:


corpus = [
    "Hello there good man!",
    "It is quite windy in London",
    "How is the weather today?"
]

tokenized_corpus = [doc.split(" ") for doc in corpus]

bm25 = BM25Okapi(tokenized_corpus)
bm25

In [6]:
query = "windy London"
tokenized_query = query.split(" ")

doc_scores = bm25.get_scores(tokenized_query)
# array([0.        , 0.93729472, 0.        ])
doc_scores

array([0.        , 0.93729472, 0.        ])

In [7]:
bm25.get_top_n(tokenized_query, corpus, n=1)

['It is quite windy in London']

In [8]:
bm25.get_top_n(tokenized_query, corpus, n=2)

['It is quite windy in London', 'How is the weather today?']

In [9]:
from rank_bm25 import BM25L

In [10]:
bm25l = BM25L(tokenized_corpus)
bm25l

In [11]:
query = "windy London"
tokenized_query = query.split(" ")

doc_scoresl = bm25l.get_scores(tokenized_query)
# array([0.        , 0.93729472, 0.        ])
doc_scoresl

array([0.        , 2.34061526, 0.        ])

In [12]:
bm25l.get_top_n(tokenized_query, corpus, n=1)

['It is quite windy in London']

In [13]:
bm25l.get_top_n(tokenized_query, corpus, n=2)

['It is quite windy in London', 'How is the weather today?']

In [14]:
from rank_bm25 import BM25Plus

In [15]:
bm25pl = BM25Plus(tokenized_corpus)
bm25pl

In [16]:
doc_scorespl = bm25pl.get_scores(tokenized_query)
# array([0.        , 0.93729472, 0.        ])
doc_scorespl

array([2.77258872, 5.3162481 , 2.77258872])

In [18]:
bm25pl.get_top_n(tokenized_query, corpus, n=1)

['It is quite windy in London']

In [19]:
bm25pl.get_top_n(tokenized_query, corpus, n=2)

['It is quite windy in London', 'How is the weather today?']

# Working with Corpus

In [22]:
import os


In [23]:
path = "F:\\donald_trump_speeches"
os.chdir(path)
os.listdir()
files=os.listdir()
files

['Trump Black History Month Speech.txt',
 'Trump CIA Speech.txt',
 'Trump Congressional Address.txt',
 'Trump CPAC Speech.txt',
 'Trump Florida Rally 2-18-17.txt',
 'Trump Immigration Speech 8-31-16.txt',
 'Trump Inauguration Speech.txt',
 'Trump National Prayer Breakfast.txt',
 'Trump Nomination Speech.txt',
 'Trump Police Chiefs Speech.txt',
 'Trump Response to Healthcare Bill Failure.txt']

In [23]:
def read_text_file(file_path):
    with open(file_path, 'r') as f:
        print(f.read())

In [26]:
corpus=[]

# iterate through all file
for file in os.listdir():
    #read_text_file(file)
    with open(file, 'r') as f:
        corpus.append(f.read())

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2863: character maps to <undefined>

In [ ]:
file1 = open("stopwords.txt", 'r')
#each_file_text=fin.read().strip()
line = file1.read()
line

In [26]:
corpus=[]

# iterate through all file
for file in os.listdir():
    f= open(file, 'r')
    corpus.append(f.read())
    f.close()

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2863: character maps to <undefined>

In [32]:
"""
try:
    with open(fName, 'rb') as f:
        reader = csv.reader(f)
        for row in reader:
            pass #do stuff here
    
except IOError:
    print "Could not read file:", fName
    
"""  

corpus=[]
line=" "

# iterate through all file
for file in os.listdir():
    f= open(file, 'r')
    try:
            line=f.read()
    except IOError:
            print("Could not read file:", file)    
    corpus.append(line)
    f.close()

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2863: character maps to <undefined>

In [33]:
corpus

['Well, the election, it came out really well. Next time we’ll triple the number or quadruple it. We want to get it over 51, right? At least 51.\n\nWell this is Black History Month, so this is our little breakfast, our little get-together. Hi Lynn, how are you? Just a few notes. During this month, we honor the tremendous history of African-Americans throughout our country. Throughout the world, if you really think about it, right? And their story is one of unimaginable sacrifice, hard work, and faith in America. I’ve gotten a real glimpse—during the campaign, I’d go around with Ben to a lot of different places I wasn’t so familiar with. They’re incredible people. And I want to thank Ben Carson, who’s gonna be heading up HUD. That’s a big job. That’s a job that’s not only housing, but it’s mind and spirit. Right, Ben? And you understand, nobody’s gonna be better than Ben.\n\nLast month, we celebrated the life of Reverend Martin Luther King, Jr., whose incredible 

In [24]:
    f= open(files[10], 'r')   # 1, 4, 7,8,9 
    try:
            line=f.read()
    except IOError:
            print("Could not read file:", file)    
    corpus.append(line)
    f.close()
    

In [27]:
for i in [1,4,7,8,9,10]:
    print(i)

1
4
7
8
9
10


In [30]:
corpus=[]
line=" "
for i in [0,2,3,5,6,10]:
    f= open(files[i], 'r')   # 1, 4, 7,8,9, Not working 
    try:
            line=f.read()
    except IOError:
            print("Could not read file:", file)    
    corpus.append(line)
    f.close()

In [31]:
corpus

['Well, the election, it came out really well. Next time we’ll triple the number or quadruple it. We want to get it over 51, right? At least 51.\n\nWell this is Black History Month, so this is our little breakfast, our little get-together. Hi Lynn, how are you? Just a few notes. During this month, we honor the tremendous history of African-Americans throughout our country. Throughout the world, if you really think about it, right? And their story is one of unimaginable sacrifice, hard work, and faith in America. I’ve gotten a real glimpse—during the campaign, I’d go around with Ben to a lot of different places I wasn’t so familiar with. They’re incredible people. And I want to thank Ben Carson, who’s gonna be heading up HUD. That’s a big job. That’s a job that’s not only housing, but it’s mind and spirit. Right, Ben? And you understand, nobody’s gonna be better than Ben.\n\nLast month, we celebrated the life of Reverend Martin Luther King, Jr., whose incredible 

In [32]:

tokenized_corpus = [doc.split(" ") for doc in corpus]

In [33]:
bm25 = BM25Okapi(tokenized_corpus)
bm25

In [34]:
query = "American Greatness is now beginning"
tokenized_query = query.split(" ")

doc_scores = bm25.get_scores(tokenized_query)
doc_scores

array([1.44114013, 3.29799168, 1.56003948, 1.5711523 , 1.55431461,
       1.05335683])

In [35]:
tn=bm25.get_top_n(tokenized_query, corpus, n=2)
tn

['Mr. Speaker, Mr. Vice President, Members of Congress, the First Lady of the United States, and Citizens of America:\nTonight, as we mark the conclusion of our celebration of Black History Month, we are reminded of our Nation\'s path toward civil rights and the work that still remains. Recent threats targeting Jewish Community Centers and vandalism of Jewish cemeteries, as well as last week\'s shooting in Kansas City, remind us that while we may be a Nation divided on policies, we are a country that stands united in condemning hate and evil in all its forms.\nEach American generation passes the torch of truth, liberty and justice --- in an unbroken chain all the way down to the present.\nThat torch is now in our hands. And we will use it to light up the world. I am here tonight to deliver a message of unity and strength, and it is a message deeply delivered from my heart.\nA new chapter of American Greatness is now beginning.\nA new national pride is sweeping across our Nation.\nAnd a

In [75]:
tn[0]

'Mr. Speaker, Mr. Vice President, Members of Congress, the First Lady of the United States, and Citizens of America:\nTonight, as we mark the conclusion of our celebration of Black History Month, we are reminded of our Nation\'s path toward civil rights and the work that still remains. Recent threats targeting Jewish Community Centers and vandalism of Jewish cemeteries, as well as last week\'s shooting in Kansas City, remind us that while we may be a Nation divided on policies, we are a country that stands united in condemning hate and evil in all its forms.\nEach American generation passes the torch of truth, liberty and justice --- in an unbroken chain all the way down to the present.\nThat torch is now in our hands. And we will use it to light up the world. I am here tonight to deliver a message of unity and strength, and it is a message deeply delivered from my heart.\nA new chapter of American Greatness is now beginning.\nA new national pride is sweeping across our Nation.\nAnd a 

In [77]:
corpus[1]

'Mr. Speaker, Mr. Vice President, Members of Congress, the First Lady of the United States, and Citizens of America:\nTonight, as we mark the conclusion of our celebration of Black History Month, we are reminded of our Nation\'s path toward civil rights and the work that still remains. Recent threats targeting Jewish Community Centers and vandalism of Jewish cemeteries, as well as last week\'s shooting in Kansas City, remind us that while we may be a Nation divided on policies, we are a country that stands united in condemning hate and evil in all its forms.\nEach American generation passes the torch of truth, liberty and justice --- in an unbroken chain all the way down to the present.\nThat torch is now in our hands. And we will use it to light up the world. I am here tonight to deliver a message of unity and strength, and it is a message deeply delivered from my heart.\nA new chapter of American Greatness is now beginning.\nA new national pride is sweeping across our Nation.\nAnd a 

In [36]:
# 1, 4, 7,8,9 exclude
fileS=['Trump Black History Month Speech.txt', 'Trump Congressional Address.txt', 'Trump CPAC Speech.txt',  'Trump Immigration Speech 8-31-16.txt',
 'Trump Inauguration Speech.txt',  'Trump Response to Healthcare Bill Failure.txt']

In [37]:
index=[]
for i in range(len(tn)):
    for j in range(len(corpus)):
        if tn[i]==corpus[j]:
            index.append(j)
    

In [38]:
for i in range(len(index)):
    print(fileS[i])

Trump Black History Month Speech.txt
Trump Congressional Address.txt


In [ ]:
# Similarly try for BM25L, BM25Plus

In [ ]:
# using Gensim package

In [39]:
!pip install gensim


[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [41]:
import gensim

In [42]:
help(gensim)

Help on package gensim:

NAME
    gensim

DESCRIPTION
    This package contains functionality to transform documents (strings) into vectors, and calculate
    similarities between documents.

PACKAGE CONTENTS
    _matutils
    corpora (package)
    downloader
    interfaces
    matutils
    models (package)
    nosy
    parsing (package)
    scripts (package)
    similarities (package)
    test (package)
    topic_coherence (package)
    utils

DATA
    logger = <Logger gensim (WARNING)>

VERSION
    4.2.0

FILE
    c:\users\ajey kumar\.conda\envs\ta\lib\site-packages\gensim\__init__.py




In [55]:
help(gensim.similarities.termsim)

Help on module gensim.similarities.termsim in gensim.similarities:

NAME
    gensim.similarities.termsim - This module provides classes that deal with term similarities.

CLASSES
    gensim.utils.SaveLoad(builtins.object)
        SparseTermSimilarityMatrix
        TermSimilarityIndex
            UniformTermSimilarityIndex
            WordEmbeddingSimilarityIndex
    
    class SparseTermSimilarityMatrix(gensim.utils.SaveLoad)
     |  SparseTermSimilarityMatrix(source, dictionary=None, tfidf=None, symmetric=True, dominant=False, nonzero_limit=100, dtype=<class 'numpy.float32'>)
     |  
     |  Builds a sparse term similarity matrix using a term similarity index.
     |  
     |  Examples
     |  --------
     |  >>> from gensim.test.utils import common_texts as corpus, datapath
     |  >>> from gensim.corpora import Dictionary
     |  >>> from gensim.models import Word2Vec
     |  >>> from gensim.similarities import SoftCosineSimilarity, SparseTermSimilarityMatrix, WordEmbeddingSimilar

In [44]:
help(gensim.topic_coherence)

Help on package gensim.topic_coherence in gensim:

NAME
    gensim.topic_coherence

DESCRIPTION
    This package contains implementation of the individual components of
    the topic coherence pipeline.

PACKAGE CONTENTS
    aggregation
    direct_confirmation_measure
    indirect_confirmation_measure
    probability_estimation
    segmentation
    text_analysis

FILE
    c:\users\ajey kumar\.conda\envs\ta\lib\site-packages\gensim\topic_coherence\__init__.py




In [40]:
from gensim.summarization.bm25 import BM25

ModuleNotFoundError: No module named 'gensim.summarization'

In [51]:
bm25gm = BM25(tokenized_corpus)
bm25gm

scores = bm25gm.get_scores(tokenized_query)
scores

[1.4411401303895046,
 3.2979916804886016,
 1.5600394753312772,
 1.571152298809557,
 1.5543146105226204,
 1.053356832738657]

In [87]:
doc_scores

array([1.44114013, 3.29799168, 1.56003948, 1.5711523 , 1.55431461,
       1.05335683])

In [88]:
best_docs = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:3]
for i, b in enumerate(best_docs):
    #print(f"rank {i+1}: {corpus[b]}")
    print(f"rank {i+1}: {fileS[b]}")

rank 1: Trump Congressional Address.txt
rank 2: Trump Immigration Speech 8-31-16.txt
rank 3: Trump CPAC Speech.txt


In [89]:
best_docs

[1, 3, 2]

In [91]:
enumerate(best_docs) ### to check?


In [ ]:
## Similarity



In [54]:
import string

In [55]:
import sklearn

In [56]:
help(sklearn)


Help on package sklearn:

NAME
    sklearn

DESCRIPTION
    Machine learning module for Python
    
    sklearn is a Python module integrating classical machine
    learning algorithms in the tightly-knit world of scientific Python
    packages (numpy, scipy, matplotlib).
    
    It aims to provide simple and efficient solutions to learning problems
    that are accessible to everybody and reusable in various contexts:
    machine-learning as a versatile tool for science and engineering.
    
    See http://scikit-learn.org for complete documentation.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _distributor_init
    _isotonic
    _loss (package)
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experimental (package)
    ext

In [59]:
help(sklearn.metrics.pairwise)

AttributeError: module 'sklearn' has no attribute 'metrics'

In [60]:
help(metrics.pairwise)

NameError: name 'metrics' is not defined

In [61]:
from sklearn.metrics.pairwise import *

In [62]:
help(sklearn.metrics.pairwise)

Help on module sklearn.metrics.pairwise in sklearn.metrics:

NAME
    sklearn.metrics.pairwise - # -*- coding: utf-8 -*-

FUNCTIONS
    additive_chi2_kernel(X, Y=None)
        Computes the additive chi-squared kernel between observations in X and Y
        
        The chi-squared kernel is computed between each pair of rows in X and Y.  X
        and Y have to be non-negative. This kernel is most commonly applied to
        histograms.
        
        The chi-squared kernel is given by::
        
            k(x, y) = -Sum [(x - y)^2 / (x + y)]
        
        It can be interpreted as a weighted difference per entry.
        
        Read more in the :ref:`User Guide <chi2_kernel>`.
        
        Notes
        -----
        As the negative of a distance, this kernel is only conditionally positive
        definite.
        
        
        Parameters
        ----------
        X : array-like of shape (n_samples_X, n_features)
        
        Y : array of shape (n_samples_Y, n_fe

In [ ]:
from scipy.spatial.distance

['braycurtis', 'canberra', 'chebyshev',
              'correlation', 'dice', 'hamming', 'jaccard', 'kulsinski',
              'mahalanobis', 'minkowski', 'rogerstanimoto', 'russellrao',
              'seuclidean', 'sokalmichener', 'sokalsneath', 'sqeuclidean',
              'yule']

In [ ]:

more
TextDistance
https://pypi.org/project/textdistance/

In [63]:
!pip install textdistance

In [64]:
import textdistance

In [65]:
help(textdistance)

Help on package textdistance:

NAME
    textdistance

DESCRIPTION
    TextDistance.
    Compute distance between sequences.
    30+ algorithms, pure python implementation, common interface.

PACKAGE CONTENTS
    algorithms (package)
    benchmark
    libraries
    utils

SUBMODULES
    base
    compression_based
    edit_based
    phonetic
    sequence_based
    simple
    token_based

DATA
    VERSION = '4.2.1'
    __license__ = 'MIT'
    __title__ = 'TextDistance'
    arith_ncd = ArithNCD({'base': 2, 'terminator': None, 'qval': 1})
    bag = Bag({'qval': 1, 'external': True})
    bwtrle_ncd = BWTRLENCD({'terminator': '\x00'})
    bz2_ncd = BZ2NCD({})
    cosine = Cosine({'qval': 1, 'as_set': False, 'external': True})
    damerau_levenshtein = DamerauLevenshtein({'qval': 1, 'test_func': <fun...
    editex = Editex({'match_cost': 0, 'group_cost': 1, 'misma..., 'X', 'Y'...
    entropy_ncd = EntropyNCD({'qval': 1, 'coef': 1, 'base': 2})
    gotoh = Gotoh({'qval': 1, 'gap_open': 1, 'gap_e

In [ ]:
pip install python-Levenshtein
import Levenshtein

In [66]:
# Clustering
from sklearn.cluster import *

In [68]:
help(sklearn.cluster)

Help on package sklearn.cluster in sklearn:

NAME
    sklearn.cluster

DESCRIPTION
    The :mod:`sklearn.cluster` module gathers popular unsupervised clustering
    algorithms.

PACKAGE CONTENTS
    _affinity_propagation
    _agglomerative
    _bicluster
    _birch
    _dbscan
    _dbscan_inner
    _feature_agglomeration
    _hierarchical_fast
    _k_means_elkan
    _k_means_fast
    _k_means_lloyd
    _kmeans
    _mean_shift
    _optics
    _spectral
    affinity_propagation_
    bicluster
    birch
    dbscan_
    hierarchical
    k_means_
    mean_shift_
    optics_
    setup
    spectral
    tests (package)

CLASSES
    sklearn.base.BaseEstimator(builtins.object)
        sklearn.cluster._affinity_propagation.AffinityPropagation(sklearn.base.ClusterMixin, sklearn.base.BaseEstimator)
        sklearn.cluster._agglomerative.AgglomerativeClustering(sklearn.base.ClusterMixin, sklearn.base.BaseEstimator)
            sklearn.cluster._agglomerative.FeatureAgglomeration(sklearn.cluster._aggl

In [56]:
import sklearn

In [57]:
from sklearn.metrics.pairwise import *

In [58]:
help(sklearn.metrics.pairwise)

Help on module sklearn.metrics.pairwise in sklearn.metrics:

NAME
    sklearn.metrics.pairwise - # -*- coding: utf-8 -*-

FUNCTIONS
    additive_chi2_kernel(X, Y=None)
        Computes the additive chi-squared kernel between observations in X and
        Y.
        
        The chi-squared kernel is computed between each pair of rows in X and Y.  X
        and Y have to be non-negative. This kernel is most commonly applied to
        histograms.
        
        The chi-squared kernel is given by::
        
            k(x, y) = -Sum [(x - y)^2 / (x + y)]
        
        It can be interpreted as a weighted difference per entry.
        
        Read more in the :ref:`User Guide <chi2_kernel>`.
        
        Notes
        -----
        As the negative of a distance, this kernel is only conditionally positive
        definite.
        
        
        Parameters
        ----------
        X : array-like of shape (n_samples_X, n_features)
        
        Y : ndarray of shape (n_samp

In [59]:
from scipy.spatial.distance

SyntaxError: invalid syntax (2614097603.py, line 1)

In [60]:
import scipy

In [61]:
help(scipy.spatial.distance)

Help on module scipy.spatial.distance in scipy.spatial:

NAME
    scipy.spatial.distance

DESCRIPTION
    Distance computations (:mod:`scipy.spatial.distance`)
    
    .. sectionauthor:: Damian Eads
    
    Function reference
    ------------------
    
    Distance matrix computation from a collection of raw observation vectors
    stored in a rectangular array.
    
    .. autosummary::
       :toctree: generated/
    
       pdist   -- pairwise distances between observation vectors.
       cdist   -- distances between two collections of observation vectors
       squareform -- convert distance matrix to a condensed one and vice versa
       directed_hausdorff -- directed Hausdorff distance between arrays
    
    Predicates for checking the validity of distance matrices, both
    condensed and redundant. Also contained in this module are functions
    for computing the number of observations in a distance matrix.
    
    .. autosummary::
       :toctree: generated/
    
       is

In [ ]:
['braycurtis', 'canberra', 'chebyshev',
              'correlation', 'dice', 'hamming', 'jaccard', 'kulsinski',
              'mahalanobis', 'minkowski', 'rogerstanimoto', 'russellrao',
              'seuclidean', 'sokalmichener', 'sokalsneath', 'sqeuclidean',
              'yule']

In [63]:
!pip3 install textdistance


[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [64]:
import textdistance

In [65]:
help(textdistance)

Help on package textdistance:

NAME
    textdistance

DESCRIPTION
    TextDistance.
    Compute distance between sequences.
    30+ algorithms, pure python implementation, common interface.

PACKAGE CONTENTS
    algorithms (package)
    benchmark
    libraries
    utils

SUBMODULES
    base
    compression_based
    edit_based
    phonetic
    sequence_based
    simple
    token_based

DATA
    VERSION = '4.3.0'
    __license__ = 'MIT'
    __title__ = 'TextDistance'
    arith_ncd = ArithNCD({'base': 2, 'terminator': None, 'qval': 1})
    bag = Bag({'qval': 1, 'external': True})
    bwtrle_ncd = BWTRLENCD({'terminator': '\x00'})
    bz2_ncd = BZ2NCD({})
    cosine = Cosine({'qval': 1, 'as_set': False, 'external': True})
    damerau_levenshtein = DamerauLevenshtein({'qval': 1, 'test_func': <fun...
    editex = Editex({'match_cost': 0, 'group_cost': 1, 'misma..., 'N', 'J'...
    entropy_ncd = EntropyNCD({'qval': 1, 'coef': 1, 'base': 2})
    gotoh = Gotoh({'qval': 1, 'gap_open': 1, 'gap_e